name = "muimedya-finance"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "muimedya_finance"
database_name = "muimedya-finance"
database_id = "d1aea268-e0f3-4dc9-b512-c96125deeb9b"
